power: reset: nvmem-reboot-mode: add CONFIG_OF dependency
Without CONFIG_OF, we get a build failure in the reboot-mode
implementation:

drivers/power/reset/reboot-mode.c: In function 'reboot_mode_register':
drivers/power/reset/reboot-mode.c:72:2: error: implicit declaration of function 'for_each_property_of_node'; did you mean 'for_each_child_of_node'? [-Werror=implicit-function-declaration]
  for_each_property_of_node(np, prop) {

Add a Kconfig dependency like we have for the other users of
CONFIG_REBOOT_MODE.

Fixes: 412708aa7ee7 ("power: reset: nvmem-reboot-mode: use NVMEM as reboot mode write interface")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Sebastian Reichel <sebastian.reichel@collabora.com>