GKI: Add update_symbol_list.sh
This script should be used to update the pixel symbol list during
development when the below error occurs:

  depmod: WARNING:
  .../vh_sched.ko needs unknown symbol idle_cpu
  ERROR: kernel module(s) need unknown symbol(s)
  Return Code: 1

When this occurs, run the following steps:

  > ./update_symbol_list.sh
  > BUILD_KERNEL=1 ./build_slider.sh

Since this updates the symbol list in aosp/, all subsequent builds needs
to use BUILD_KERNEL=1 until the new symbol list is merged.

Bug: 186572003
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Ia5992b2bbc8bc44233ae29a5849323c12d2b55e4