soc: google: hardlockup-debug: use raw_spin_trylock
Use raw_spin_trylock instead of do_raw_spin_trylock to
fix build break when CONFIG_DEBUG_SPINLOCK is enabled.

Fixes:
ERROR: modpost: "do_raw_spin_trylock" [drivers/soc/google/hardlockup-debug.ko] undefined!

Signed-off-by: Jonglin Lee <jonglin@google.com>
Change-Id: I6b4dcfc6175ccf53521a1938791ed48e31c3ba1a